name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # Trigger deployment when changes are pushed to the main branch

jobs:
  deploy:
    name: Deploy to Firebase
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Use the Node.js version compatible with your project

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: |
          npm install

      # Step 4: Build the Project (if applicable)
      - name: Build Project
        run: |
          npm run build

      # Step 5: Deploy to Firebase Hosting
      - name: Deploy to Firebase Hosting
        uses: w9jds/firebase-action@v12.9.0
        with:
          args: deploy --only hosting
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
